import Icon from './ui/Icon.jsx';

const MATERIAL_TO_LUCIDE = {
  home: 'Home',
  home_work: 'Building2',
  landscape: 'Mountain',
  search: 'Search',
  location_on: 'MapPin',
  square_foot: 'Maximize2',
  bed: 'Bed',
  shower: 'Bath',
  crop: 'Crop',
  straighten: 'Ruler',
  chevron_right: 'ChevronRight',
  keyboard_arrow_down: 'ChevronDown',
  keyboard_arrow_left: 'ChevronLeft',
  account_circle: 'User',
  admin_panel_settings: 'ShieldCheck',
  dashboard: 'LayoutDashboard',
  add: 'Plus',
  person: 'User',
  badge: 'IdCard',
  apartment: 'Building',
  filter_list: 'SlidersHorizontal',
  light_mode: 'Sun',
  dark_mode: 'Moon',
  youtube: 'Youtube',
  facebook: 'Facebook',
  twitter: 'Twitter',
  instagram: 'Instagram',
  linkedin: 'Linkedin',
  edit: 'Pencil',
  close: 'X',
  delete: 'Trash2',
  check: 'Check',
  arrow_back: 'ArrowLeft',
  arrow_forward: 'ArrowRight',
  visibility: 'Eye',
  visibility_off: 'EyeOff',
  phone: 'Phone',
  email: 'Mail',
  star: 'Star',
  favorite: 'Heart',
  share: 'Share2',
  upload: 'Upload',
  image: 'Image',
  description: 'FileText',
  warning: 'AlertCircle',
  check_circle: 'CheckCircle',
  info: 'Info',
  schedule: 'Clock',
  logout: 'LogOut',
  settings: 'Settings',
  trending_up: 'TrendingUp',
  group: 'Users',
  payments: 'DollarSign',
  bar_chart: 'BarChart3',
  more_horiz: 'MoreHorizontal',
};

export default function MaterialIcon({ children, className = '', style }) {
  const lucideName = MATERIAL_TO_LUCIDE[children] || 'AlertCircle';
  const sizeMatch = className.match(/text-(\w+)/);
  const sizeMap = { sm: 14, base: 16, lg: 20, xl: 24, '2xl': 28 };
  const size = sizeMap[sizeMatch?.[1]] || 20;
  return <Icon name={lucideName} size={size} className={className} />;
}
