CREATE TYPE user_role AS ENUM ('USER', 'BROKER', 'ADMIN');
CREATE TYPE user_status AS ENUM ('ACTIVE', 'LOCKED');
CREATE TYPE property_status AS ENUM ('AVAILABLE', 'RENTED', 'SOLD', 'HIDDEN');
CREATE TYPE media_type AS ENUM ('IMAGE', 'VIDEO_LINK', 'VIDEO_FILE');
CREATE TYPE report_status AS ENUM ('PENDING', 'RESOLVED');
CREATE TYPE audit_action AS ENUM ('CREATE', 'UPDATE', 'DELETE');

CREATE TABLE users (
    id UUID PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(150),
    phone VARCHAR(30),
    email VARCHAR(254) NOT NULL UNIQUE,
    role user_role NOT NULL DEFAULT 'USER',
    status user_status NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE properties (
    id UUID PRIMARY KEY,
    broker_id UUID NOT NULL REFERENCES users(id),
    category_id BIGINT NOT NULL REFERENCES categories(id),
    title VARCHAR(255) NOT NULL,
    address VARCHAR(500) NOT NULL,
    price NUMERIC(19, 2) NOT NULL CHECK (price >= 0),
    status property_status NOT NULL DEFAULT 'AVAILABLE',
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE media (
    id UUID PRIMARY KEY,
    property_id UUID NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    media_type media_type NOT NULL,
    url VARCHAR(2048) NOT NULL,
    is_thumbnail BOOLEAN NOT NULL DEFAULT FALSE,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE saved_properties (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    property_id UUID NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    saved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, property_id)
);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id UUID NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    reporter_id UUID NOT NULL REFERENCES users(id),
    reason TEXT NOT NULL,
    status report_status NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_logs (
    id UUID PRIMARY KEY,
    actor_id UUID NOT NULL REFERENCES users(id),
    action audit_action NOT NULL,
    entity_name VARCHAR(100) NOT NULL,
    entity_id UUID,
    old_value JSONB,
    new_value JSONB,
    "timestamp" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_properties_broker_id ON properties (broker_id);
CREATE INDEX idx_properties_category_status_created ON properties (category_id, status, created_at DESC);
CREATE INDEX idx_properties_status_created ON properties (status, created_at DESC);
CREATE INDEX idx_properties_attributes_gin ON properties USING GIN (attributes);
CREATE INDEX idx_media_property_id ON media (property_id);
CREATE INDEX idx_reports_status_created ON reports (status, created_at DESC);
CREATE INDEX idx_reports_property_id ON reports (property_id);
CREATE INDEX idx_audit_logs_actor_timestamp ON audit_logs (actor_id, "timestamp" DESC);
CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_name, entity_id);

INSERT INTO categories (name, slug, description) VALUES
    ('Trọ', 'tro', 'Phòng trọ và nhà trọ'),
    ('Nhà', 'nha', 'Nhà ở, nhà cho thuê và nhà bán'),
    ('Đất', 'dat', 'Đất ở và các loại đất khác');
