export const MOCK_PROPERTIES = [
  {
    id: 'p-586',
    title: 'Nhà phố 1 trệt 2 lầu, KDC 586',
    address: 'Phường Trà Vinh, TP. Trà Vinh',
    ward: 'phuong-tra-vinh',
    category: 'nha',
    transaction: 'sale',
    price: 3.65,
    priceLabel: '3,650 tỷ',
    statusLabel: 'Mới',
    area: 100,
    size: '5 x 20m',
    bedrooms: 4,
    direction: 'Đông Nam',
    legal: 'Sổ hồng riêng',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80',
    description: 'Nhà mới xây, thiết kế hiện đại, nội thất cao cấp. Khu dân cư an ninh, gần trường học, chợ và bệnh viện.',
    broker: { name: 'Nguyễn Văn Toàn', phone: '0912345678', email: 'toan@congtinland.vn', rating: '4.9 (128 đánh giá)', responseTime: '5 phút' },
    amenities: ['Sân để xe', 'Tủ bếp', 'Máy bơm nước', 'Cửa bảo vệ'],
    summary: {
      location: 'Tọa lạc tại trung tâm Phường Trà Vinh, thuận tiện di chuyển đến chợ, trường học và các tiện ích đô thị.',
      amenities: 'Nội thất cao cấp, thiết kế hiện đại với phòng bếp rộng rãi và khu vệ sinh khép kín.',
      convenience: 'Khu dân cư văn minh, an ninh 24/7, phù hợp cho gia đình và nhà đầu tư dài hạn.',
    },
  },
  {
    id: 'p-ql53',
    title: 'Đất nền mặt tiền Quốc lộ 53',
    address: 'Phường Long Đức, TP. Trà Vinh',
    ward: 'phuong-long-duc',
    category: 'dat',
    transaction: 'sale',
    price: 2.25,
    priceLabel: '2,250 tỷ',
    statusLabel: 'Nổi bật',
    area: 150,
    size: '5 x 30m',
    bedrooms: 0,
    direction: 'Tây Nam',
    legal: 'Thổ cư',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80',
    description: 'Lô đất vuông vức, mặt tiền rộng, thuận tiện kinh doanh hoặc xây nhà ở lâu dài.',
    broker: { name: 'Trần Mỹ Linh', phone: '0908899777', email: 'linh@congtinland.vn', rating: '4.8 (76 đánh giá)', responseTime: '8 phút' },
    summary: {
      location: 'Mặt tiền Quốc lộ 53, khu vực Phường Long Đức có hạ tầng đang phát triển mạnh.',
      amenities: 'Đất thổ cư 100%, pháp lý rõ ràng, không vướng quy hoạch.',
      convenience: 'Giao thông thuận tiện, gần khu công nghiệp và trung tâm thương mại.',
    },
  },
  {
    id: 'p-mc',
    title: 'Căn hộ Chung cư Minh Châu',
    address: 'Phường Nguyệt Hóa, TP. Trà Vinh',
    ward: 'phuong-nguyet-hoa',
    category: 'nha',
    transaction: 'rent',
    price: 0.012,
    priceLabel: '12 triệu/tháng',
    statusLabel: 'Cho thuê',
    area: 72,
    size: '2PN',
    bedrooms: 2,
    direction: 'Đông',
    legal: 'Hợp đồng thuê',
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80',
    description: 'Căn hộ đủ nội thất, ban công thoáng, phù hợp gia đình trẻ hoặc chuyên gia làm việc tại trung tâm.',
    broker: { name: 'Lê Minh Khang', phone: '0934567890', email: 'khang@congtinland.vn', rating: '4.7 (54 đánh giá)', responseTime: '10 phút' },
    amenities: ['Giường', 'Tủ lạnh', 'Máy lạnh', 'Wifi', 'Nước nóng', 'Tủ quần áo', 'Bếp từ'],
    summary: {
      location: 'Tọa lạc tại Phường Nguyệt Hóa, gần trung tâm thương mại và các tiện ích đô thị.',
      amenities: 'Đầy đủ nội thất hiện đại, ban công đón gió Đông thoáng mát.',
      convenience: 'Phù hợp gia đình trẻ hoặc chuyên gia, bảo vệ 24/7, thang máy.',
    },
  },
  {
    id: 'p-pg',
    title: 'Nhà phố khu dân cư Phú Gia',
    address: 'Phường Long Đức, TP. Trà Vinh',
    ward: 'phuong-long-duc',
    category: 'nha',
    transaction: 'sale',
    price: 4.2,
    priceLabel: '4,200 tỷ',
    statusLabel: 'Giá tốt',
    area: 120,
    size: '6 x 20m',
    bedrooms: 4,
    direction: 'Nam',
    legal: 'Sổ hồng riêng',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80',
    description: 'Nhà góc hai mặt tiền, khu dân cư hoàn thiện hạ tầng, thích hợp vừa ở vừa kinh doanh.',
    broker: { name: 'Phạm Quốc Huy', phone: '0987654321', email: 'huy@congtinland.vn', rating: '4.9 (91 đánh giá)', responseTime: '4 phút' },
    amenities: ['Sân vườn', 'Gara xe hơi', 'Sân thượng', 'Hệ thống camera'],
    summary: {
      location: 'Khu dân cư Phú Gia tại Phường Long Đức, hạ tầng hoàn thiện, đường nội bộ trải nhựa.',
      amenities: 'Nhà góc hai mặt tiền, thông gió tự nhiên, diện tích sử dụng rộng rãi.',
      convenience: 'Thích hợp vừa ở vừa kinh doanh, gần chợ và trường học.',
    },
  },
  {
    id: 'p-vuon',
    title: 'Đất vườn Long Đức',
    address: 'Phường Long Đức, TP. Trà Vinh',
    ward: 'phuong-long-duc',
    category: 'dat',
    transaction: 'sale',
    price: 1.35,
    priceLabel: '1,350 tỷ',
    statusLabel: 'Giảm giá',
    area: 300,
    size: '10 x 30m',
    bedrooms: 0,
    direction: 'Tây',
    legal: 'Đất cây lâu năm',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
    description: 'Khu đất yên tĩnh, đường xe hơi, phù hợp làm nhà vườn hoặc đầu tư dài hạn.',
    broker: { name: 'Trần Mỹ Linh', phone: '0908899777', email: 'linh@congtinland.vn', rating: '4.8 (76 đánh giá)', responseTime: '8 phút' },
  },
  {
    id: 'p-cau-ke',
    title: 'Nhà mới đường Nguyễn Đáng',
    address: 'Phường Hòa Thuận, TP. Trà Vinh',
    ward: 'phuong-hoa-thuan',
    category: 'nha',
    transaction: 'sale',
    price: 2.98,
    priceLabel: '2,980 tỷ',
    statusLabel: 'Mới',
    area: 80,
    size: '4 x 20m',
    bedrooms: 3,
    direction: 'Bắc',
    legal: 'Sổ hồng riêng',
    image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=80',
    description: 'Nhà hoàn thiện, khu dân cư hiện hữu, pháp lý rõ ràng và bàn giao nhanh.',
    broker: { name: 'Nguyễn Văn Toàn', phone: '0912345678', email: 'toan@congtinland.vn', rating: '4.9 (128 đánh giá)', responseTime: '5 phút' },
  },
  {
    id: 'p-tro-dbp',
    title: 'Nhà trọ Điện Biên Phủ — sát ĐH Trà Vinh',
    address: 'Phường Nguyệt Hóa, TP. Trà Vinh',
    ward: 'phuong-nguyet-hoa',
    category: 'tro',
    transaction: 'rent',
    price: 0.0015,
    priceLabel: '1,5 triệu/tháng',
    statusLabel: 'Cho thuê',
    area: 18,
    size: '18m²',
    bedrooms: 1,
    direction: 'Đông Nam',
    legal: 'Hợp đồng thuê',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=900&q=80',
    description: 'Phòng trọ sạch sẽ, gần Đại học Trà Vinh, toilet khép kín, an ninh tốt.',
    broker: { name: 'Lê Minh Khang', phone: '0934567890', email: 'khang@congtinland.vn', rating: '4.7 (54 đánh giá)', responseTime: '10 phút' },
    rooms: [
      { label: 'Phòng P.01', price: 1500000, available: true },
      { label: 'Phòng P.02', price: 1500000, available: false },
      { label: 'Phòng P.03', price: 1600000, available: true },
    ],
    amenities: ['Giường', 'Tủ lạnh', 'Máy lạnh', 'Wifi', 'Nước nóng', 'Tủ quần áo', 'Gác'],
    costs: {
      electricity: { value: '3.500đ/kWh' },
      water: { value: '60.000đ/người/tháng' },
      service: { value: '100.000đ/tháng' },
      parking: { value: '50.000đ/xe/tháng' },
    },
    conditions: {
      toilet: 'Khép kín',
      hours: 'Tự do 24/7',
      washer: 'Giặt chung khu vực',
      window: 'Có cửa sổ thoáng',
      balcony: 'Không có',
      pets: 'Không nuôi',
      parking: 'Xe máy',
      ev: 'Không',
    },
    summary: {
      location: 'Tọa lạc tại hẻm yên tĩnh đường Điện Biên Phủ, Phường Nguyệt Hóa — chỉ 5 phút đến Đại học Trà Vinh và gần các quán ăn, tiệm tạp hóa.',
      amenities: 'Phòng đủ nội thất cơ bản gồm giường, tủ lạnh, máy lạnh và wifi tốc độ cao. Gác lửng mở rộng không gian lưu trữ.',
      convenience: 'An ninh tốt, chủ nhà thân thiện, phù hợp sinh viên và người đi làm. Hẻm thông xe máy, gần trường và bệnh viện.',
    },
  },
  {
    id: 'p-tro-hoa-thuan',
    title: 'Phòng trọ Hòa Thuận — nội thất đầy đủ',
    address: 'Phường Hòa Thuận, TP. Trà Vinh',
    ward: 'phuong-hoa-thuan',
    category: 'tro',
    transaction: 'rent',
    price: 0.002,
    priceLabel: '2 triệu/tháng',
    statusLabel: 'Cho thuê',
    area: 22,
    size: '22m²',
    bedrooms: 1,
    direction: 'Nam',
    legal: 'Hợp đồng thuê',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=80',
    description: 'Phòng trọ mới xây, đầy đủ nội thất, khu vực yên tĩnh, gần chợ và siêu thị Hòa Thuận.',
    broker: { name: 'Võ Hoàng Nam', phone: '0923456789', email: 'nam@congtinland.vn', rating: '4.8 (39 đánh giá)', responseTime: '7 phút' },
    rooms: [
      { label: 'Phòng A1', price: 2000000, available: true },
      { label: 'Phòng A2', price: 2000000, available: true },
      { label: 'Phòng A3', price: 2200000, available: false },
    ],
    amenities: ['Giường', 'Tủ lạnh', 'Máy lạnh', 'Wifi', 'Nước nóng', 'Tủ quần áo', 'Kệ bếp'],
    costs: {
      electricity: { value: '3.500đ/kWh' },
      water: { value: '50.000đ/người/tháng' },
      service: { value: 'Miễn phí', free: true },
      parking: { value: '60.000đ/xe/tháng' },
    },
    conditions: {
      toilet: 'Khép kín',
      hours: 'Tự do',
      washer: 'Máy giặt chung',
      window: 'Có cửa sổ',
      balcony: 'Có ban công nhỏ',
      pets: 'Không nuôi',
      parking: 'Xe máy, xe đạp',
      ev: 'Có chỗ sạc',
    },
    summary: {
      location: 'Nằm trên đường chính khu vực Phường Hòa Thuận, cách chợ Hòa Thuận 3 phút đi bộ, gần siêu thị và trường tiểu học.',
      amenities: 'Phòng mới xây năm 2023, nội thất đầy đủ và hiện đại. Máy lạnh Daikin tiết kiệm điện, nước nóng riêng từng phòng.',
      convenience: 'Khu dân cư văn minh, hàng xóm thân thiện. Phù hợp cặp đôi hoặc người đi làm. Có máy giặt chung và bãi giữ xe an toàn.',
    },
  },
];

export const BROKER_DASHBOARD = {
  activeListings: 18,
  pendingLeads: 7,
  conversion: '22%',
};

export const MOCK_USERS = [
  {
    id: 'u-admin',
    username: 'admin',
    fullName: 'Nguyễn Minh Khoa',
    email: 'khoa@congtinland.vn',
    phone: '02943999888',
    role: 'ADMIN',
    status: 'ACTIVE',
    avatarUrl: '',
  },
  {
    id: 'u-broker-1',
    username: 'toan',
    fullName: 'Nguyễn Văn Toàn',
    email: 'toan@congtinland.vn',
    phone: '0912345678',
    role: 'BROKER',
    status: 'ACTIVE',
    avatarUrl: '',
  },
  {
    id: 'u-broker-2',
    username: 'linh',
    fullName: 'Trần Mỹ Linh',
    email: 'linh@congtinland.vn',
    phone: '0908899777',
    role: 'BROKER',
    status: 'ACTIVE',
    avatarUrl: '',
  },
];

export const MOCK_ADMIN_BROKERS = [
  {
    id: 'b-1',
    username: 'toan',
    fullName: 'Nguyễn Văn Toàn',
    email: 'toan@congtinland.vn',
    phone: '0912345678',
    role: 'BROKER',
    status: 'ACTIVE',
    avatarUrl: '',
  },
  {
    id: 'b-2',
    username: 'linh',
    fullName: 'Trần Mỹ Linh',
    email: 'linh@congtinland.vn',
    phone: '0908899777',
    role: 'BROKER',
    status: 'ACTIVE',
    avatarUrl: '',
  },
  {
    id: 'b-3',
    username: 'khang',
    fullName: 'Lê Minh Khang',
    email: 'khang@congtinland.vn',
    phone: '0934567890',
    role: 'BROKER',
    status: 'ACTIVE',
    avatarUrl: '',
  },
  {
    id: 'b-4',
    username: 'huy',
    fullName: 'Phạm Quốc Huy',
    email: 'huy@congtinland.vn',
    phone: '0987654321',
    role: 'BROKER',
    status: 'ACTIVE',
    avatarUrl: '',
  },
  {
    id: 'b-5',
    username: 'nam',
    fullName: 'Võ Hoàng Nam',
    email: 'nam@congtinland.vn',
    phone: '0923456789',
    role: 'BROKER',
    status: 'ACTIVE',
    avatarUrl: '',
  },
];
