export const MOCK_PROPERTIES = [
  {
    id: 'p-586',
    title: 'Nhà phố 1 trệt 2 lầu, KDC 586',
    address: 'Phường 7, TP. Trà Vinh',
    ward: 'phuong-7',
    category: 'house',
    transaction: 'sale',
    price: 3.65,
    priceLabel: '3,650 tỷ',
    statusLabel: 'Mới',
    area: 100,
    size: '5 x 20m',
    bedrooms: 4,
    direction: 'Đông Nam',
    legal: 'Sổ hồng riêng',
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80',
    description: 'Nhà mới xây, thiết kế hiện đại, nội thất cao cấp. Khu dân cư an ninh, gần trường học, chợ và bệnh viện.',
    broker: { name: 'Nguyễn Văn Toàn', phone: '0912345678', email: 'toan@congtinland.vn', rating: '4.9 (128 đánh giá)', responseTime: '5 phút' },
  },
  {
    id: 'p-ql53',
    title: 'Đất nền mặt tiền Quốc lộ 53',
    address: 'Xã Long Đức, TP. Trà Vinh',
    ward: 'long-duc',
    category: 'land',
    transaction: 'sale',
    price: 2.25,
    priceLabel: '2,250 tỷ',
    statusLabel: 'Nổi bật',
    area: 150,
    size: '5 x 30m',
    bedrooms: 0,
    direction: 'Tây Nam',
    legal: 'Thổ cư',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80',
    description: 'Lô đất vuông vức, mặt tiền rộng, thuận tiện kinh doanh hoặc xây nhà ở lâu dài.',
    broker: { name: 'Trần Mỹ Linh', phone: '0908899777', email: 'linh@congtinland.vn', rating: '4.8 (76 đánh giá)', responseTime: '8 phút' },
  },
  {
    id: 'p-mc',
    title: 'Căn hộ Chung cư Minh Châu',
    address: 'Phường 5, TP. Trà Vinh',
    ward: 'phuong-7',
    category: 'apartment',
    transaction: 'rent',
    price: 0.012,
    priceLabel: '12 triệu/tháng',
    statusLabel: 'Cho thuê',
    area: 72,
    size: '2PN',
    bedrooms: 2,
    direction: 'Đông',
    legal: 'Hợp đồng thuê',
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80',
    description: 'Căn hộ đủ nội thất, ban công thoáng, phù hợp gia đình trẻ hoặc chuyên gia làm việc tại trung tâm.',
    broker: { name: 'Lê Minh Khang', phone: '0934567890', email: 'khang@congtinland.vn', rating: '4.7 (54 đánh giá)', responseTime: '10 phút' },
  },
  {
    id: 'p-pg',
    title: 'Nhà phố khu dân cư Phú Gia',
    address: 'Càng Long, Trà Vinh',
    ward: 'cang-long',
    category: 'house',
    transaction: 'sale',
    price: 4.2,
    priceLabel: '4,200 tỷ',
    statusLabel: 'Giá tốt',
    area: 120,
    size: '6 x 20m',
    bedrooms: 4,
    direction: 'Nam',
    legal: 'Sổ hồng riêng',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80',
    description: 'Nhà góc hai mặt tiền, khu dân cư hoàn thiện hạ tầng, thích hợp vừa ở vừa kinh doanh.',
    broker: { name: 'Phạm Quốc Huy', phone: '0987654321', email: 'huy@congtinland.vn', rating: '4.9 (91 đánh giá)', responseTime: '4 phút' },
  },
  {
    id: 'p-vuon',
    title: 'Đất vườn Long Đức',
    address: 'Xã Long Đức, TP. Trà Vinh',
    ward: 'long-duc',
    category: 'land',
    transaction: 'sale',
    price: 1.35,
    priceLabel: '1,350 tỷ',
    statusLabel: 'Giảm giá',
    area: 300,
    size: '10 x 30m',
    bedrooms: 0,
    direction: 'Tây',
    legal: 'Đất cây lâu năm',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
    description: 'Khu đất yên tĩnh, đường xe hơi, phù hợp làm nhà vườn hoặc đầu tư dài hạn.',
    broker: { name: 'Trần Mỹ Linh', phone: '0908899777', email: 'linh@congtinland.vn', rating: '4.8 (76 đánh giá)', responseTime: '8 phút' },
  },
  {
    id: 'p-cau-ke',
    title: 'Nhà mới đường Nguyễn Đáng',
    address: 'Cầu Kè, Trà Vinh',
    ward: 'cau-ke',
    category: 'house',
    transaction: 'sale',
    price: 2.98,
    priceLabel: '2,980 tỷ',
    statusLabel: 'Mới',
    area: 80,
    size: '4 x 20m',
    bedrooms: 3,
    direction: 'Bắc',
    legal: 'Sổ hồng riêng',
    image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=80',
    description: 'Nhà hoàn thiện, khu dân cư hiện hữu, pháp lý rõ ràng và bàn giao nhanh.',
    broker: { name: 'Nguyễn Văn Toàn', phone: '0912345678', email: 'toan@congtinland.vn', rating: '4.9 (128 đánh giá)', responseTime: '5 phút' },
  },
];

export const BROKER_DASHBOARD = {
  activeListings: 18,
  pendingLeads: 7,
  conversion: '22%',
};
